name: Client
on: 
  workflow_dispatch:
    inputs:
      user:
        required: true
        type: string
      version:
        required: true
        type: string
      lib_version:
        required: true
        type: choice
        options:
          - 1.9.0
      debug:
        required: false
        type: boolean
        default: false
      run_id:
        required: true
        type: string
      platform:
        required: true
        type: choice
        options:
          - windows
          - macos
          - linux
          - android
          - all

env:
  FLUTTER_VERSION: 3.22.x

jobs:
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        pkg: [zip, msix]
    if: ${{ inputs.platform == 'windows' || inputs.platform == 'all' }}
    runs-on: windows-latest
    steps:
      - name: Clone siren
        uses: actions/checkout@v4
        with:
          path: siren
          repository: intxff/siren
          token: ${{ secrets.ACTION_TOKEN }}
      - name: Clone siren-users
        uses: actions/checkout@v4
        with:
          path: siren-users
          repository: intxff/siren-users
          token: ${{ secrets.ACTION_TOKEN }}
      - name: Set up flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: false 
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version-file: "siren-users/go.mod"
      - name: download libsingbox
        uses: dawidd6/action-download-artifact@v5
        with:
          workflow: libs.yml
          run_id: ${{ inputs.run_id }}
          name: ${{ format('libsingbox_windows_amd64_{0}', inputs.lib_version) }}
          github_token: ${{ secrets.ACTION_TOKEN }}
      - name: debug 
        if: ${{ inputs.debug }}
        uses: mxschmitt/action-tmate@v3
      - name: compile client
        run: |
          cd siren
          make ci_windows LIB_VERSION=${{ inputs.lib_version }} VERSION=${{ inputs.version }} PKG=${{ matrix.pkg }}
